<?php

namespace AppBundle\Repository;

/**
 * GuestBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestBookRepository extends \Doctrine\ORM\EntityRepository
{
}
